name: sgi-tp-service:build

on:
  push:
    branches: [ main ]
    paths:
      - 'sgi-tp-service/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/template:build-backend-service.yml
    secrets: inherit
    with:
      project_name: sgi-tp-service
