name: sgi-esb:build

on:
  push:
    branches: [ main ]
    paths:
      - 'sgi-esb/**'
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build all Maven artifacts (JARs + CARs)
        run: mvn clean package -Pci -DskipTests -Dmaven.javadoc.skip=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=didiez/sgi-esb
          TAG=latest

          docker build -t $IMAGE_NAME:$TAG -f Dockerfile .
          docker push $IMAGE_NAME:$TAG
