apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgi-esb.fullname" . }}
  labels:
    {{- include "sgi-esb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    {{- include "sgi-esb.selectorLabels" . | nindent 4 }}